Repository kyma-project/kyma-companion-manager, pull requests merged in 2024-07, with the labels that each got.

#1 chore: Scaffolding Kyma Companion Manager
  .dockerignore
  .gitignore
  .golangci.yml
  Dockerfile
  Makefile
  PROJECT
  README.md
  api/v1alpha1/companion_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_companions.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/default/kustomization.yaml
  config/default/manager_metrics_patch.yaml
  config/default/metrics_service.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/companion_editor_role.yaml
  config/rbac/companion_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1alpha1_companion.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  internal/controller/companion_controller.go
  internal/controller/companion_controller_test.go
  internal/controller/suite_test.go
  internal/controller/unit_test.go
  internal/controller/utils.go
  internal/controller/utils_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/utils/options.go
  test/utils/utils.go
Labels: cla: yes, size/XXL, lgtm

#6 chore: updated codeowners and added PR title lint job
  .github/workflows/lint-pr-title.yml
  CODEOWNERS
Labels: cla: yes, lgtm, size/M

#8 chore: fixed codeowners to enable auto-assignment of reviewers
  CODEOWNERS
Labels: cla: yes, lgtm, size/XS

#9 chore: added unit-test and lint job
  .github/workflows/lint-go.yml
  .github/workflows/test.yml
  .golangci.yml
  Makefile
  api/v1alpha1/companion_types.go
  api/v1alpha1/groupversion_info.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_companions.yaml
  internal/controller/companion_controller.go
  internal/controller/companion_controller_test.go
  internal/controller/suite_test.go
  internal/controller/unit_test.go
  test/e2e/e2e_test.go
  test/utils/options.go
  test/utils/utils.go
Labels: cla: yes, lgtm, size/XL

#10 chore: scaffolded integration tests
  .golangci.yml
  go.mod
  go.sum
  internal/controller/companion_controller_test.go
  internal/controller/suite_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/integration/controller/controller_test.go
  test/integration/integration.go
  test/utils/utils.go
Labels: cla: yes, lgtm, size/XL

#11 chore: created a deployment for companion backend
  .gitignore
  .golangci.yml
  Dockerfile
  cmd/main.go
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/priority-class.yaml
  config/prometheus/monitor.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/default.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1alpha1_companion.yaml
  go.mod
  go.sum
  hack/tools.go
  internal/backendmanager/config.go
  internal/backendmanager/manager.go
  internal/backendmanager/manager_test.go
  internal/backendmanager/mocks/manager.go
  internal/backendmanager/utils.go
  internal/backendmanager/utils_test.go
  internal/controller/companion_controller.go
  internal/controller/companion_controller_test.go
  internal/controller/unit_test.go
  internal/label/label.go
  internal/label/label_test.go
  pkg/env/config.go
  pkg/env/config_test.go
  pkg/equality/equality.go
  pkg/equality/equality_test.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/deployment/deployment.go
  pkg/k8s/mocks/client.go
  pkg/k8s/secret/secret.go
  pkg/utils/utils.go
  test/integration/controller/controller_test.go
  test/integration/integration.go
  test/utils/utils.go
Labels: cla: yes, size/XXL, lgtm

#7 chore: update for REUSE compliance
  .reuse/dep5
  README.md
Labels: cla: yes, lgtm, size/S

#19 feat: design the companion manager cr
  .golangci.yml
  api/v1alpha1/companion_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_companions.yaml
  config/samples/default.yaml
Labels: cla: yes, lgtm, size/L
